#!/bin/python3

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))
    rev = []
    for i in range(0,n):
        rev.append(arr[n-1-i])
    print(' '.join(map(str, rev)))